---
# tasks file for ntp
- name: ensure the ntp package is installed
  package:
    name: ntp
    state: present
  tags: [ntp]

- name: ensure that ntp is running and enabled
  service:
    name: ntpd
    state: started
    enabled: yes
  tags: [ntp]
